#!/usr/bin/env node

const fs = require('fs')
const axios = require('axios')
let foo = require('./step2').foo

function readPFile(str) {
	return new Promise ((resolve, reject) => {
		fs.readFile(str, 'utf8',  function(err, data) {
			resolve(data)
		})
	})
	.then((res) => JSON.parse(res))
}

function writePFile(str, obj) {
	fs.writeFile(str, JSON.stringify(obj))
}

console.log('ichart api does not work anymore.')
// axios.get('http://ichart.yahoo.com/table.csv')
// .then((res) => console.log("the Api does not function anymore"))

foo()