#!/usr/bin/env node

const fs = require('fs')

function readPFile(str) {
	return new Promise ((resolve, reject) => {
		fs.readFile(str, 'utf8',  function(err, data) {
			resolve(data)
		})
	})
	.then((res) => JSON.parse(res))
}

function writePFile(str, obj) {
	fs.writeFile(str, JSON.stringify(obj))
}


function getPortTotalWorth() {
	let counter = 0
	let total = 0
	let arr = []
	new Promise((resolve, request) => {
		resolve(readPFile('./public/staticFiles/portfolio.json'))
	})
	.then((res) => res.map(( dat) => {
		let port = readPFile('./public/staticFiles/funds.json')
		port.then((val) => {
			val.forEach((valFunds) => {
				if(dat.symbol === valFunds.symbol) {
					new Promise((fulfill, rej) => {
						let fundsP = readPFile('./public/staticFiles/fund_prices.json')
						fundsP
						.then((valFundPrices) => {
							valFundPrices.forEach((valFundPrice) => {
								if(valFundPrice.symbol === dat.symbol) {
									let totalSharePrice = dat.shares * valFundPrice.price
									total = total + totalSharePrice
									console.log(valFunds.name +':'+ dat.shares + ' shares at $' + valFundPrice.price + 
										' ea. -- $' + totalSharePrice.toFixed(2))
									if(counter === 5) {
										console.log('Total: $', total.toFixed(2)) 
										writePFile('./public/staticFiles/combinedData.json', arr)
									} else {
										counter ++
										arr.push({"symbol": valFundPrice.symbol, "name": valFunds.name, 
											"shares": dat.shares, "price": valFundPrice.price, 
											"totalPrice": totalSharePrice, "assetClass": valFunds.assetClass})
									}
								}
							})
						})
					})
				}
			})
		})
	}))
}

getPortTotalWorth()




exports.getPortTotalWorth = getPortTotalWorth
